version: '3.8'

services:

  app-postgres:
    image: "postgres:14.0-alpine"
    container_name: app-postgres
    volumes:
      - app-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password



  app-spring:

    image: "dockerimtiredofinventingnames/jwt_auth_demo:latest"
    container_name: app-spring

    environment:
      - DB_SERVER=app-postgres
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

    ports:
      - 8080:8080

    links:
      - app-postgres


volumes:
  app-data: