version: '3.8'

services:

  app-postgres:
    image: "postgres:14.0-alpine"
    container_name: app-postgres
    volumes:
      - app-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=jwt_auth_demo_DB
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=Qwerty123



  app-spring:

    build: .
    container_name: app-spring

    ports:
      - 8080:8080

    links:
      - app-postgres


volumes:
  app-data: