spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://${DB_SERVER}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver


runtime_variables:
  secret_key: secret