spring:
  jpa:
    hibernate:
      ddl-auto: none
  database: h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: false
      path: /h2-console

runtime_variables:
  secret_key: secret