spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  datasource:
    initialization-mode: always
    platform: postgres
    url: jdbc:postgresql://localhost:5432/jwt_auth_demo_DB?currentSchema=public
    username: user
    password: Qwerty123
    driverClassName: org.postgresql.Driver


runtime_variables:
  secret_key: secret