drop table if exists authority CASCADE;
drop table if exists user_details CASCADE;
drop table if exists message CASCADE;

create table authority(
                          authority_id bigint generated by default as identity,
                          authority_name varchar(20) not null,
                          user_details_id bigint not null,
                          primary key (authority_id)
);

create table message(
                        message_id bigint generated by default as identity,
                        created_at timestamp,
                        message_content varchar(255),
                        username varchar(20),
                        primary key (message_id)
);

create table user_details(
                             user_details_id bigint generated by default as identity,
                             non_expired boolean,
                             non_locked boolean,
                             credentials_non_expired boolean,
                             enabled boolean,
                             password varchar(255) not null,
                             username varchar(20) not null,
                             primary key (user_details_id)
);

alter table user_details add constraint unique_username unique(username);
alter table authority add constraint authority_foreign_key foreign key (user_details_id) references user_details;
alter table message add constraint user_foreign_key foreign key (username) references user_details (username);
